2025-05-11 18:46:34 +0300 [ERROR] {"timestamp": "2025-05-11T18:46:34.424962", "error_type": "AttributeError", "error_message": "'Logger' object has no attribute 'log_activity'", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\src\\middleware\\logging_middleware.py\", line 320, in dispatch\n    await self.activity_middleware._log_activity(request, response, process_time)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\src\\middleware\\logging_middleware.py\", line 185, in _log_activity\n    await activity_logger.log_activity(\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Logger' object has no attribute 'log_activity'\n", "user_id": null, "additional_context": {"user_agent": "PostmanRuntime/7.43.4", "referer": null, "content_type": "application/json", "accept_language": null}, "request": {"method": "POST", "url": "http://127.0.0.1:8000/api/v1/auth/google", "path": "/api/v1/auth/google", "query_params": {}, "client_host": "127.0.0.1", "headers": {"content-type": "application/json", "accept": "application/json", "user-agent": "PostmanRuntime/7.43.4", "postman-token": "04c79c2e-462f-4c37-b4f7-236af5ba8d35", "host": "127.0.0.1:8000", "accept-encoding": "gzip, deflate, br", "connection": "keep-alive", "content-length": "54"}}}
2025-05-11 18:59:03 +0300 [ERROR] {"timestamp": "2025-05-11T18:59:03.747653", "error_type": "NameError", "error_message": "name 'logger' is not defined", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\src\\middleware\\logging_middleware.py\", line 321, in dispatch\n    await self.activity_middleware._log_activity(request, response, process_time)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\src\\middleware\\logging_middleware.py\", line 178, in _log_activity\n    await activity_logger.log_activity(\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\src\\utils\\logging\\activity_logger.py\", line 119, in log_activity\n    logger.info(json.dumps(log_entry))\n    ^^^^^^\nNameError: name 'logger' is not defined\n", "user_id": null, "additional_context": {"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36", "referer": null, "content_type": null, "accept_language": "en-US,en;q=0.9"}, "request": {"method": "GET", "url": "http://localhost:8000/api/v1/auth/google", "path": "/api/v1/auth/google", "query_params": {}, "client_host": "127.0.0.1", "headers": {"host": "localhost:8000", "connection": "keep-alive", "sec-ch-ua": "\"Google Chrome\";v=\"135\", \"Not-A.Brand\";v=\"8\", \"Chromium\";v=\"135\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9", "cookie": "[REDACTED]"}}}
2025-05-11 19:52:50 +0300 [ERROR] {"timestamp": "2025-05-11T19:52:50.249378", "message": "Google OAuth login error: 'is_verified' is an invalid keyword argument for User", "error_type": "oauth_error", "user_id": null, "stack_trace": null, "metadata": {}}
2025-05-11 19:59:24 +0300 [ERROR] {"timestamp": "2025-05-11T19:59:24.826650", "message": "Google OAuth login error: 'theme' is an invalid keyword argument for UserPreference", "error_type": "oauth_error", "user_id": null, "stack_trace": null, "metadata": {}}
2025-05-11 23:44:39 +0300 [ERROR] {"timestamp": "2025-05-11T23:44:39.715627", "error_type": "ValueError", "error_message": "[TypeError(\"'coroutine' object is not iterable\"), TypeError('vars() argument must have __dict__ attribute')]", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 324, in jsonable_encoder\n    data = dict(obj)\n           ^^^^^^^^^\nTypeError: 'coroutine' object is not iterable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 329, in jsonable_encoder\n    data = vars(obj)\n           ^^^^^^^^^\nTypeError: vars() argument must have __dict__ attribute\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\src\\middleware\\logging_middleware.py\", line 314, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 163, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 149, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 185, in __call__\n    with collapse_excgroups():\n         ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 187, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\src\\middleware\\rate_limit_middleware.py\", line 91, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 163, in call_next\n    raise app_exc\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 149, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 735, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 327, in app\n    content = await serialize_response(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 201, in serialize_response\n    return jsonable_encoder(response_content)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 289, in jsonable_encoder\n    encoded_value = jsonable_encoder(\n                    ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 289, in jsonable_encoder\n    encoded_value = jsonable_encoder(\n                    ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 303, in jsonable_encoder\n    jsonable_encoder(\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 289, in jsonable_encoder\n    encoded_value = jsonable_encoder(\n                    ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\Documents\\Projects\\personal\\katiba360\\katiba360-backend\\venv\\Lib\\site-packages\\fastapi\\encoders.py\", line 332, in jsonable_encoder\n    raise ValueError(errors) from e\nValueError: [TypeError(\"'coroutine' object is not iterable\"), TypeError('vars() argument must have __dict__ attribute')]\n", "user_id": null, "additional_context": {"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36", "referer": "http://localhost:8000/docs", "content_type": null, "accept_language": "en-US,en;q=0.9"}, "request": {"method": "GET", "url": "http://localhost:8000/api/v1/constitution/search?query=the%20national%20flag&limit=10&offset=0&highlight=true", "path": "/api/v1/constitution/search", "query_params": {"query": "the national flag", "limit": "10", "offset": "0", "highlight": "true"}, "client_host": "127.0.0.1", "headers": {"host": "localhost:8000", "connection": "keep-alive", "sec-ch-ua-platform": "\"Windows\"", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36", "accept": "application/json", "sec-ch-ua": "\"Google Chrome\";v=\"135\", \"Not-A.Brand\";v=\"8\", \"Chromium\";v=\"135\"", "sec-ch-ua-mobile": "?0", "sec-fetch-site": "same-origin", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "referer": "http://localhost:8000/docs", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9", "cookie": "[REDACTED]"}}}
